### PR TITLE
docs: Fix docs/install-freisa.sh

### LINKED ISSUE #23: [BUG]: install-freisa.sh fails if Docker is already installed
### Description of the bug

It looks like the `install-freisa.sh` script does not fail gracefully if [Docker Engine](https://docs.docker.com/engine/) was already installed.

### Steps To Reproduce

1. Launch `install-freisa.sh`
   ```bash
   curl -fsSL https://raw.githubusercontent.com/B-AROL-O/ble-testsuite/main/docs/install-freisa.sh | sh
   ```
3. Launch `install-freisa.sh` a second time
   ```bash
   curl -fsSL https://raw.githubusercontent.com/B-AROL-O/ble-testsuite/main/docs/install-freisa.sh | sh
   ```
4. Observe the messages on the console

```text
ubuntu@rpird201b:~$ curl -fsSL https://raw.githubusercontent.com/B-AROL-O/ble-testsuite/main/docs/install-freisa.sh | sh
+ sudo apt-get update
Hit:1 http://ports.ubuntu.com/ubuntu-ports jammy InRelease
Hit:2 http://ports.ubuntu.com/ubuntu-ports jammy-updates InRelease                                  
Hit:3 http://ports.ubuntu.com/ubuntu-ports jammy-backports InRelease                                
Hit:4 http://ports.ubuntu.com/ubuntu-ports jammy-security InRelease                                 
Hit:5 https://download.docker.com/linux/ubuntu jammy InRelease                                      
Get:6 https://pkgs.tailscale.com/stable/ubuntu jammy InRelease             
Fetched 6557 B in 3s (2340 B/s)                      
Reading package lists... Done
...
+ curl -fsSL https://get.docker.com -o get-docker.sh
+ sudo sh ./get-docker.sh --dry-run
# Executing docker install script, commit: e5543d473431b782227f8908005543bb4389b8de
Warning: the "docker" command appears to already exist on this system.

If you already have Docker installed, this script can cause trouble, which is
why we're displaying this warning and provide the opportunity to cancel the
installation.

If you installed the current Docker package using this script and are using it
again to update Docker, you can safely ignore this message.

You may press Ctrl+C now to abort this script.
+ sleep 20
apt-get update -qq >/dev/null
DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
install -m 0755 -d /etc/apt/keyrings
curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | gpg --dearmor --yes -o /etc/apt/keyrings/docker.gpg
chmod a+r /etc/apt/keyrings/docker.gpg
echo "deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable" > /etc/apt/sources.list.d/docker.list
apt-get update -qq >/dev/null
DEBIAN_FRONTEND=noninteractive apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin docker-ce-rootless-extras docker-buildx-plugin >/dev/null
+ sudo sh ./get-docker.sh
# Executing docker install script, commit: e5543d473431b782227f8908005543bb4389b8de
Warning: the "docker" command appears to already exist on this system.

If you already have Docker installed, this script can cause trouble, which is
why we're displaying this warning and provide the opportunity to cancel the
installation.

If you installed the current Docker package using this script and are using it
again to update Docker, you can safely ignore this message.

You may press Ctrl+C now to abort this script.
+ sleep 20
+ sh -c apt-get update -qq >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 22366 (apt-get)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
ubuntu@rpird201b:~$
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by gmacario**
## 📑 Description

Closes #23 

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

**Comment by gmacario** [comment]
Ping @davmacario

**Comment by gmacario** [comment]
Ping @davmacario please kindly review this PR

**Review by davmacario — APPROVED** [review]

**Comment by gmacario** [comment]
Thanks @davmacario, merging PR

P.S.: Shouldn't be time for you to go to sleep?

**Comment by davmacario** [comment]
> P.S.: Shouldn't be time for you to go to sleep?

This is just Alta Scuola Politecnica's fault...

**Pull request merged**
